services:
  php-app:
    build:
      context: .
    container_name: php-app
    restart: unless-stopped
    init: true
    # Exposes PHP-FPM on port 9000 (for use with a web server like nginx)
    expose:
      - "9000"
    # env_file: ./.env  # Uncomment if .env file exists
    networks:
      - appnet
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

# Network for inter-service communication
networks:
  appnet:
    driver: bridge

# Persistent storage for MySQL
volumes:
  mysql-data:
